### PR TITLE
Add modified callow

### PR DESCRIPTION
**Pull request by cleverusername82**
Callow wasn't working for the websites I tested it on so I added a keyboard package and had it press enter at the end of every entry as a fix. I was going to make this a pull request in callow but you said leave it alone so I'll drop it here on the small chance it's a help. 

Thank you for this and all your projects!

### CODE REVIEW

**Comment by maximousblk** [comment]
Callow was getting spammed so I archived it for the time being. Do you want to send your pr there? I can unarchive it for you.

**Comment by cleverusername82** [comment]
If you'd like me to, I'm not too experienced so I wasn't sure if it's a good enough solution to actually put onto the project or not.

**Comment by maximousblk** [comment]
Sorry for my late response @cleverusername82.

Have you tried your solution and did it fix the problem? If yes, then it is good enough for me.

Just tell me when you want to open the pull request, I'll unarchive the repository.

I'll merge this pr anyway

**Comment by cleverusername82** [comment]
I can now or whenever during the weekend, thank you.

**Comment by maximousblk** [comment]
I have unarchived the repository, you can send your pull request now.

(hope I don't get spammed again)

**Pull request merged**
